### ISSUE TITLE
ng-pick-datetime

### ISSUE THREAD

**Issue by mgechev** [angular/ngcc-validation#117]
```
ERROR in @ViewChild predicate cannot be interpreted
```

**Comment by mgechev** [comment]
No longer an ngcc failure.

**Comment by mgechev** [comment]
FYI https://github.com/DanielYKPan/date-time-picker/issues/636

**Comment by spitfjre** [comment]
With latest version `rc.4` you get postinstall compilation errors:

```
Error: Error on worker #6: Error: Failed to compile entry-point ng-pick-datetime due to compilation errors:
node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of OwlDialogModule, but could not be resolved to an NgModule class
node_modules/@angular/cdk/a11y/a11y-module.d.ts(9,22): error TS-996002: Appears in the NgModule.imports of OwlDialogModule, but could not be resolved to an NgModule class
node_modules/@angular/cdk/overlay/overlay-module.d.ts(9,22): error TS-996002: Appears in the NgModule.imports of OwlDialogModule, but could not be resolved to an NgModule class
node_modules/@angular/cdk/portal/portal-directives.d.ts(84,22): error TS-996002: Appears in the NgModule.imports of OwlDialogModule, but could not be resolved to an NgModule class
node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of OwlDateTimeModule, but could not be resolved to an NgModule class
node_modules/@angular/cdk/overlay/overlay-module.d.ts(9,22): error TS-996002: Appears in the NgModule.imports of OwlDateTimeModule, but could not be resolved to an NgModule class
node_modules/ng-pick-datetime/dialog/dialog.module.js(14,5): error TS-996002: Appears in the NgModule.imports of OwlDateTimeModule, but itself has errors
node_modules/@angular/cdk/a11y/a11y-module.d.ts(9,22): error TS-996002: Appears in the NgModule.imports of OwlDateTimeModule, but could not be resolved to an NgModule class
node_modules/@angular/cdk/platform/platform-module.d.ts(8,22): error TS-996002: Appears in the NgModule.imports of NativeDateTimeModule, but could not be resolved to an NgModule class
node_modules/ng-pick-datetime/date-time/adapter/native-date-time.module.js(13,5): error TS-996002: Appears in the NgModule.imports of OwlNativeDateTimeModule, but itself has errors

    at ClusterWorker.compile (/home/spitfjre/Workspace/mysvg/frontend/node_modules/@angular/compiler-cli/ngcc/src/main.js:170:27)
    at Worker.<anonymous> (/home/spitfjre/Workspace/mysvg/frontend/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:41:42)
    at Worker.emit (events.js:210:5)
    at process.<anonymous> (internal/cluster/worker.js:30:12)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
    at ClusterMaster.onWorkerMessage (/home/spitfjre/Workspace/mysvg/frontend/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /home/spitfjre/Workspace/mysvg/frontend/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/home/spitfjre/Workspace/mysvg/frontend/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/home/spitfjre/Workspace/mysvg/frontend/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/spitfjre/Workspace/mysvg/frontend/node_modules/tslib/tslib.js:117:57)
    at /home/spitfjre/Workspace/mysvg/frontend/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/spitfjre/Workspace/mysvg/frontend/node_modules/tslib/tslib.js:106:16)
    at EventEmitter.<anonymous> (/home/spit
```

**Comment by gkalpak** [comment]
OOC, what does the exact `postinstall` script look like?
Also, are you saying this doesn't happen with rc.3 (or just you haven't tried)?

**Comment by spitfjre** [comment]
`"postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"`

There was no problem in rc.3.

**Comment by gkalpak** [comment]
The originally reported `ng-pick-datetime` error seems to have been fixed. @spitfjre, if you are still running into problems with the latest versions of Angular and `ng-pick-datetime`, please open a new issue on the [angular/angular](https://github.com/angular/angular/issues) repo.
