### ISSUE TITLE
@nebular/theme: runtime error

### ISSUE THREAD

**Issue by rayman1104** [angular/ngcc-validation#529]
After adding NgModule import for @nebular/theme, e2e starts failing with the next runtime error:
```bash
$ ng e2e nebulartheme-ngcc
      ...
      - Expected [ Entry({ level: SEVERE, message: 'http://localhost:4200/main.js 223:43
          Error: Can't resolve all parameters for NbScrollStrategyOptions: (?, ?, ?, ?, ?).
          at getUndecoratedInjectableFactory (http://localhost:4200/vendor.js:37759:15)
          at injectableDefOrInjectorDefFactory (http://localhost:4200/vendor.js:37749:16)
          at providerToFactory (http://localhost:4200/vendor.js:37813:24)
          at providerToRecord (http://localhost:4200/vendor.js:37775:19)
          at R3Injector.push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.processProvider (http://localhost:4200/vendor.js:37676:22)
          at http://localhost:4200/vendor.js:37651:79
          at http://localhost:4200/vendor.js:26322:93
          at Array.forEach (<anonymous>)
          at deepForEach (http://localhost:4200/vendor.js:26322:11)
          at _loop_1 (http://localhost:4200/vendor.js:37651:21)', timestamp: 1573125221882, type: '' }) ] not to contain <jasmine.objectContaining(Object({ level: SEVERE }))>.
      ...
```
Also described here: https://github.com/akveo/nebular/issues/2041
PR with repro: https://github.com/angular/ngcc-validation/pull/526

**Comment by petebacondarwin** [comment]
`@nebular/theme` is now working after https://github.com/angular/angular/pull/33732
