### ISSUE TITLE
angular-froala-wysiwyg - failure

### ISSUE THREAD

**Issue by petebacondarwin** [angular/ngcc-validation#57]
Here is the stack trace from the failure to compile this library.

I think we need to change `findExportedNameOfNode()` to use a `ReflectionHost` to interact with the source code. Currently it is assuming the source is TS. See https://github.com/angular/angular/blob/a8d84660e5088f0dca1845e24a0422fed080aa81/packages/compiler-cli/src/ngtsc/imports/src/find_export.ts#L14

```
Compiling angular-froala-wysiwyg : module as esm5
Error: Failed to find exported name of node (function FroalaEditorModule() {
    }) in '/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/angular-froala-wysiwyg/editor/editor.module.js'.
    at Object.findExportedNameOfNode (/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/find_export.js:33:19)
    at LogicalProjectStrategy.emit (/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:194:38)
    at ReferenceEmitter.emit (/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:41:44)
    at Object.toR3Reference (/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:137:32)
    at NgModuleDecoratorHandler._toR3Reference (/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:287:31)
    at /Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:132:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:132:38)
    at Object.analyzeDecorators (/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/ngcc/src/analysis/util.js:73:34)
    at DecorationAnalyzer.analyzeClass (/Users/pete/dev/angular/ngcc-validation/angular-froala-wysiwyg-ngcc/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:126:27)
```

**Comment by petebacondarwin** [comment]
Probably same issue for `angular-font-awesome`.

**Comment by earshinov** [comment]
For angular-froala-wysiwyg you can track these:

- PR: https://github.com/froala/angular-froala-wysiwyg/pull/329
- https://github.com/froala/angular-froala-wysiwyg/issues/307

**Comment by petebacondarwin** [comment]
I tried applying this fix from @alxhub https://github.com/alxhub/angular/commit/a5696f99c973484f19249d229ddb49bcd5fcd731 but this did not solve the problem...

**Comment by petebacondarwin** [comment]
Looks like a bug in`Esm5ReflectionHost.getDeclarationOfIdentifier()` for this particular shape.

**Comment by petebacondarwin** [comment]
Now the failure for this package is the classic "Importing removed Renderer".

**Comment by mgechev** [comment]
That's great! I can open a PR to then tomorrow/Monday.

**Comment by mgechev** [comment]
FYI https://github.com/froala/angular-froala-wysiwyg/issues/347

**Comment by mgechev** [comment]
FYI https://github.com/froala/angular-froala-wysiwyg/pull/349

**Comment by gkalpak** [comment]
This is now fixed and compiles successfully.
